name: "mxbai_xs_ensemble"
platform: "ensemble"
max_batch_size: 512

input [
  { name: "QUERY",     data_type: TYPE_STRING, dims: [1] },
  { name: "DOCUMENTS", data_type: TYPE_STRING, dims: [-1] },
  { name: "TOP_N",     data_type: TYPE_INT32,  dims: [1] }
]

output [
  { name: "scores",  data_type: TYPE_FP32, dims: [-1] },
  { name: "indices", data_type: TYPE_INT64, dims: [-1] }
]

ensemble_scheduling {
  step [
    {
      model_name: "mxbai_xs_hf"
      model_version: 1
      input_map  { key: "QUERY"     value: "QUERY" }
      input_map  { key: "DOCUMENTS" value: "DOCUMENTS" }
      input_map  { key: "TOP_N"     value: "TOP_N" }
      output_map { key: "scores" value: "scores" }
      output_map { key: "indices" value: "indices" }
    }
  ]
}
