name: "mxbai_xs_postproc"
backend: "python"
max_batch_size: 0

input [
  { name: "logits",  data_type: TYPE_FP32, dims: [-1, 1] },
  { name: "top_n",   data_type: TYPE_INT32, dims: [1] }
]
output [
  { name: "scores",  data_type: TYPE_FP32, dims: [-1, 1] },
  { name: "indices", data_type: TYPE_INT64, dims: [-1] }
]

instance_group [{ kind: KIND_CPU, count: 1 }]
