name: "mxbai_xs_hf"
backend: "python"
max_batch_size: 512

input [
  { name: "QUERY",     data_type: TYPE_STRING, dims: [1] },
  { name: "DOCUMENTS", data_type: TYPE_STRING, dims: [-1] },
  { name: "TOP_N",     data_type: TYPE_INT32, dims: [1] }
]

output [
  { name: "scores",  data_type: TYPE_FP32, dims: [-1] },
  { name: "indices", data_type: TYPE_INT64, dims: [-1] }
]

instance_group [{ kind: KIND_GPU, gpus: [0], count: 1 }]

dynamic_batching {
  preferred_batch_size: [16, 32, 64, 128, 256, 512]
  max_queue_delay_microseconds: 2000
}
